### ISSUE TITLE
Add modules.list

### ISSUE THREAD

**Issue by ZarTek-Creole** [ValwareIRC/valware-unrealircd-mods#1]
Could you add to your repository a modules.list containing all your modules to be able to add to unrealircd's modules.sources.list please?

**Comment by ValwareIRC** [comment]
Heya, thanks for your interest in my modules. All the modules I make that are actually useable are already in unreal's official third-party repository, except for `react`, which will be available in unrealircd in the next update (which I suspect should be soon).

This repo exists primarily to house the `README.md`s for the modules commited to that repository, any module which is listed here, which is not already in the official third-party repo, is useless (like `ayyy.c`) or discontinued (like `supersecureonly.c`).

You should install my modules directly using the included modules sources list =]

Have a great evening

**Comment by ValwareIRC** [comment]
I'm so sorry, in my sleepiness, I managed to mix up `react` with `channel-context` (`+draft/channel-context`) which was being added into unrealircd source.

It's still available through the third-party repository though, I should note =]
