### ISSUE TITLE
fix type error should be "...Reemplaza 's's con 'f's y 't's con 'd's...

### ISSUE THREAD

**Issue by isruus** [ValwareIRC/valware-unrealircd-mods#2]
https://github.com/ValwareIRC/valware-unrealircd-mods/blob/7808049f9576494df70ad5aa0a3c2fd7987f59c7/elmer/elmer-es.c#L66

**Comment by ValwareIRC** [comment]
Thank you so much for bringing this to my attention! I have updated it in the repository now with what you said =]
