### ISSUE TITLE
Add whois info for nicklocked users

### ISSUE THREAD

**Issue by adamus1red** [ValwareIRC/valware-unrealircd-mods#3]
**Is your module request related to a problem? Please describe.**
There is no easy way to check if a user is nicklocked without having to search the server log.

**Describe the solution you'd like**
It would be beneficial for a oper view-only whois line is added as part of the nicklock process so that it is easy to check if a user has been nicklocked.

Something like `* Idiot :is nicklocked. Nickname was NotIdiot`

**Comment by ValwareIRC** [comment]
Hi there, thank you so much for your recommendation.

I have updated the module and made a PR to the unrealircd-contrib repo, so it's just a case of waiting now =]
There is now a line in the target's `/WHOIS` saying that the nick is locked, viewable only to opers.

In addition to that, thinking about your request, I've also added a `-list` option to the `/NICKLOCK` command, so you can also just `/NICKLOCK -list` to view all nicklock'd users.

Hope I helped! Have a great day

**Comment by ValwareIRC** [comment]
Hiya!

Just thought I'd drop a notification that the patch PR'd to the unrealircd-contrib repository has been merged. You can now:
` ./unrealircd module upgrade third/nicklock`

Have a great weekend!

**Comment by adamus1red** [comment]
Thanks @ValwareIRC
