### ISSUE TITLE
My shiny new module request

### ISSUE THREAD

**Issue by ValwareIRC** [ValwareIRC/valware-unrealircd-mods#5]
on behalf of Mahjong

**Please describe, in full, the functions and features of the module you would like to request**
 on seven and solanum and other ircd there is this special version of moderated where you add +z to the +m and only operators can see unvoiced messages under this mode

I would like to have a usermode with the same functionality as +m except ops and higher can see messages from non-voiced users.

**If you are requesting a feature that exists in another IRC project, please link to it below**
https://github.com/freenode/ircd-seven

**Describe alternatives you've considered**

**Additional context**

**Comment by adamus1red** [comment]
Isn't `third/auditorum` similar to that

**Comment by ValwareIRC** [comment]
yes but does not show joins and parts

**Comment by ValwareIRC** [comment]
oops wrong button lol

**Comment by ValwareIRC** [comment]
Done:
https://github.com/ValwareIRC/valware-unrealircd-mods/tree/main/reduced-moderation
